using System.Collections.Generic;
using System.Linq;
using System.Text;
using GProtobuf.Generator.Analysis;

namespace GProtobuf.Generator.V2.Helpers
{
    /// <summary>Emits one depth-counter guard class per unique handler type for <c>AutoReentrancyGuard = true</c>.</summary>
    internal static class AmbientHandlerGuardGenerator
    {
        /// <summary>Global namespace for generated guard types.</summary>
        public const string GuardNamespace = "GProtobuf.__Generated.AmbientGuards";

        public static string GeneratedFileName => "AmbientHandlerGuards.g.cs";

        public static string GetGuardTypeReference(AmbientHandlerDefinition handler)
        {
            return $"global::{GuardNamespace}.{GetGuardTypeName(handler.HandlerTypeFullName)}";
        }

        public static string GetGuardTypeName(string handlerTypeFullName)
        {
            return "__GProtoHandlerGuard_" + Sanitize(handlerTypeFullName);
        }

        public static string Generate(AmbientHandlerRegistry registry)
        {
            if (registry == null || registry.IsEmpty) return null;

            var uniqueHandlers = registry.GetAllSorted()
                .Select(h => h.HandlerTypeFullName)
                .Distinct()
                .OrderBy(x => x, System.StringComparer.Ordinal)
                .ToList();

            if (uniqueHandlers.Count == 0) return null;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine($"namespace {GuardNamespace}");
            sb.AppendLine("{");

            foreach (var handlerFullName in uniqueHandlers)
            {
                var guardName = GetGuardTypeName(handlerFullName);
                sb.AppendLine($"    /// <summary>Re-entrancy guard for AmbientSerializationHandler '{handlerFullName}'.</summary>");
                sb.AppendLine($"    internal static class {guardName}");
                sb.AppendLine("    {");
                sb.AppendLine("        [ThreadStatic] private static int _depth;");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine("        public static bool Enter() => _depth++ == 0;");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine("        public static void Exit() => _depth--;");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string Sanitize(string fullName)
        {
            var sb = new StringBuilder(fullName.Length);
            foreach (var ch in fullName)
            {
                if (char.IsLetterOrDigit(ch) || ch == '_') sb.Append(ch);
                else sb.Append('_');
            }
            return sb.ToString();
        }
    }
}
